In [1]:
using PyCall

In [2]:
py"""
import numpy    #this is a test case
xs = numpy.ones((2))
"""

In [3]:
yo = PyArray(py"xs"o) #testing reading from numpy array 

2-element PyArray{Float64, 1}:
 1.0
 1.0

In [5]:
col = Vector{Float64}(yo)

2-element Vector{Float64}:
 1.0
 1.0

In [6]:
col

2-element Vector{Float64}:
 1.0
 1.0

In [7]:
using JLD2
some_data = col
@save "xs.jld2" some_data

In [1]:
@load "wl_grid"

LoadError: LoadError: UndefVarError: @load not defined
in expression starting at In[1]:1

In [15]:
using HDF5

In [19]:
data = h5read("C:/Users/pravn/Dropbox/masters/python-code/galah-file-read-test/data.h5","wl_grid")

4096-element Vector{Float64}:
 4713.805085503763
 4713.851112715211
 4713.897139926658
 4713.943167138106
 4713.989194349554
 4714.035221561002
 4714.08124877245
 4714.127275983898
 4714.173303195345
 4714.219330406793
 4714.265357618241
 4714.311384829689
 4714.357412041137
    ⋮
 4901.780217056724
 4901.826244268172
 4901.8722714796195
 4901.918298691067
 4901.964325902515
 4902.010353113963
 4902.056380325411
 4902.102407536859
 4902.1484347483065
 4902.194461959754
 4902.240489171202
 4902.28651638265

In [21]:
using JLD2, FileIO, SharedArrays

In [22]:
Δλ = 7 
subordinate_line_vac = 6105.7
li_vac = 6709.702
#wls = Float32.(load("wl_grid.jld2")["wl_grid"])
wls = data
subordinate_line_mask = subordinate_line_vac - Δλ .< wls .< subordinate_line_vac + Δλ
npix = sum(.! subordinate_line_mask) #n pixels that are not masked 
wl_grid = SharedArray{Float32}(npix) 
wl_grid .= wls[.! subordinate_line_mask]
line_mask = li_vac - Δλ .< wl_grid .< li_vac + Δλ

4096-element BitVector:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [13]:
some_data

2-element Vector{Float64}:
 1.0
 1.0

In [9]:
julia_mat = Matrix(xs)

LoadError: MethodError: no method matching (Matrix{T} where T)(::PyArray{Float64, 1})
Closest candidates are:
  (Array{T, N} where T)(::AbstractArray{S, N}) where {S, N} at boot.jl:470
  (Matrix{T} where T)(::Union{LinearAlgebra.QR, LinearAlgebra.QRCompactWY}) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\qr.jl:434
  (Matrix{T} where T)(::LinearAlgebra.LQ) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\lq.jl:120
  ...

In [10]:
py"""   
import numpy as np
import astropy.io.fits as pyfits
import matplotlib.pyplot as plt
import glob
"""

LoadError: PyError ($(Expr(:escape, :(ccall(#= C:\Users\pravn\.julia\packages\PyCall\BD546\src\pyeval.jl:38 =# @pysym(:PyEval_EvalCode), PyPtr, (PyPtr, PyPtr, PyPtr), o, globals, locals))))) <class 'ModuleNotFoundError'>
ModuleNotFoundError("No module named 'astropy'")
  File "C:\Users\pravn\.julia\packages\PyCall\BD546\src\pyeval.jl", line 3, in <module>
    const Py_eval_input = 258
